[versions]
apache-commons-lang3 = "3.20.0"
apache-commons-text = "1.15.0"

fastutil = "8.5.18"

gson = "2.13.0"

guava = "33.5.0-jre"

javapoet = "0.11.0"

joml = "1.10.8"

jetbrains-annotations = "26.0.2-1"

junit-jupiter = "5.13.4"

lombok = "1.18.42"

machinemc-nbt = "2.0.0"
machinemc-paklet = "1.2.3"
machinemc-scriptive = "1.3"

netty = "4.2.10.Final"

[libraries]
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons-lang3" }
apache-commons-text = { module = "org.apache.commons:commons-text", version.ref = "apache-commons-text" }

fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

guava = { module = "com.google.guava:guava", version.ref = "guava" }

javapoet = { module = "com.palantir.javapoet:javapoet", version.ref = "javapoet" }

joml = { module = "org.joml:joml", version.ref = "joml" }

jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

machinemc-nbt-core = { module = "org.machinemc:nbt-core", version.ref = "machinemc-nbt" }
machinemc-nbt-parser = { module = "org.machinemc:nbt-parser", version.ref = "machinemc-nbt" }

machinemc-paklet-api = { module = "org.machinemc:paklet-api", version.ref = "machinemc-paklet" }
machinemc-paklet-core = { module = "org.machinemc:paklet-core", version.ref = "machinemc-paklet" }
machinemc-paklet-processor = { module = "org.machinemc:paklet-processor", version.ref = "machinemc-paklet" }
machinemc-paklet-plugin = { module = "org.machinemc:paklet-plugin", version.ref = "machinemc-paklet" }

machinemc-scriptive-core = { module = "org.machinemc:scriptive-core", version.ref = "machinemc-scriptive" }
machinemc-scriptive-gson = { module = "org.machinemc:scriptive-gson", version.ref = "machinemc-scriptive" }
machinemc-scriptive-nbt = { module = "org.machinemc:scriptive-nbt", version.ref = "machinemc-scriptive" }

netty = { module = "io.netty:netty-all", version.ref = "netty" }
